Update manifest and pipeline
pagopa/bpd-io-backend-test pull request #3
Opened 2021-06-22 10:32 UTC by ElfoLiNk

2021-06-22 15:45 UTC, pasqualedevita approved these changes

2021-06-24 08:21 UTC, pasqualedevita approved these changes

2021-06-24 08:24 UTC, pasqualedevita requested changes

2021-06-24 08:24 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +    settingsXmlsecureFileName: '$(SETTINGS_XML_RO_SECURE_FILE_NAME)'
```suggestion
    mavenGoals: 'deploy'
    settingsXmlsecureFileName: '$(SETTINGS_XML_RW_SECURE_FILE_NAME)'
```

2021-06-24 08:28 UTC, ElfoLiNk commented on .devops/deploy-pipelines.yml
> +    settingsXmlsecureFileName: '$(SETTINGS_XML_RO_SECURE_FILE_NAME)'
No need for deploy the jar

2021-06-24 13:41 UTC, closed without merging